% autoexec_cfg generated by Configure AFC. Add your local preferences here.

def.language = 'EN';
def.fileNamingScheme = '%E_%S_%C';
def.deviceID = -1;
def.bits=24;
msg.measure_msg= '--- CORRECT ---';
def.variableCheck = 0;
def.markIntervalDelay = 0.1; %Compensation for delay using audioplayer
